spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: courier
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  message-source: courier
  message-source-header: message-source
  delivery-time-ms: 10000
  notification-topic:
    name: notification-topic
